### ISSUE TITLE
HTML tags in message

### ISSUE THREAD

**Issue by codegaze** [tandibar/ui-bootstrap-alerts#1]
Is there any way to have html tags inside the message?
i tried to add ng-bind-html-unsafe but didnt work

thnx!

**Comment by codegaze** [comment]
sanitize it is! :)

**Comment by tandibar** [comment]
So it worked out for you? Can i close this issue?

**Comment by codegaze** [comment]
Yes. I used https://docs.angularjs.org/api/ngSanitize if my memory serves me right.
